spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/user_management
    username: user_management_user
    password: 1q2w3e
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.xml

management:
  user:
    password:
      length: 10
      strength: SPECIAL
    roles:
      - name: ADMIN
        isAdmin: true
      - name: USER